/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCpagripPostbackRouteImport } from './routes/api/cpagrip-postback'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCpagripPostbackRoute = ApiCpagripPostbackRouteImport.update({
  id: '/api/cpagrip-postback',
  path: '/api/cpagrip-postback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earn': typeof EarnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/api/cpagrip-postback': typeof ApiCpagripPostbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earn': typeof EarnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/api/cpagrip-postback': typeof ApiCpagripPostbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/earn': typeof EarnRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRoute
  '/api/cpagrip-postback': typeof ApiCpagripPostbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/earn'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/api/cpagrip-postback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/earn'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/api/cpagrip-postback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/earn'
    | '/login'
    | '/signup'
    | '/tasks'
    | '/api/cpagrip-postback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EarnRoute: typeof EarnRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRoute
  ApiCpagripPostbackRoute: typeof ApiCpagripPostbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cpagrip-postback': {
      id: '/api/cpagrip-postback'
      path: '/api/cpagrip-postback'
      fullPath: '/api/cpagrip-postback'
      preLoaderRoute: typeof ApiCpagripPostbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EarnRoute: EarnRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  ApiCpagripPostbackRoute: ApiCpagripPostbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
